# Generated by Django 4.2.7 on 2023-11-23 15:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Brand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='نام')),
                ('name_slug', models.SlugField(allow_unicode=True, blank=True, editable=False, max_length=255, null=True, verbose_name='اسلاگ نام')),
                ('link', models.CharField(blank=True, max_length=255, null=True, verbose_name='لینک')),
                ('image', models.ImageField(blank=True, null=True, upload_to='store/brands/', verbose_name='تصویر')),
                ('seo_title', models.CharField(blank=True, max_length=255, null=True, verbose_name='سئو - نام')),
                ('seo_keywords', models.CharField(blank=True, max_length=255, null=True, verbose_name='سئو - کلمات کلیدی')),
                ('seo_description', models.CharField(blank=True, max_length=255, null=True, verbose_name='سئو - توضیحات')),
            ],
            options={
                'verbose_name': 'برند',
                'verbose_name_plural': 'برند ها',
            },
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('parent_tree', models.CharField(blank=True, editable=False, max_length=1000, null=True, verbose_name='درخت رابطه')),
                ('name', models.CharField(max_length=255, verbose_name='نام')),
                ('name_slug', models.SlugField(allow_unicode=True, blank=True, editable=False, max_length=255, null=True, verbose_name='اسلاگ نام')),
                ('link', models.CharField(blank=True, max_length=255, null=True, verbose_name='لینک')),
                ('image', models.ImageField(blank=True, null=True, upload_to='store/categories/', verbose_name='تصویر')),
                ('seo_title', models.CharField(blank=True, max_length=255, null=True, verbose_name='سئو - نام')),
                ('seo_keywords', models.CharField(blank=True, max_length=255, null=True, verbose_name='سئو - کلمات کلیدی')),
                ('seo_description', models.CharField(blank=True, max_length=255, null=True, verbose_name='سئو - توضیحات')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='parent_category', to='store.category', verbose_name='دسته مادر')),
            ],
            options={
                'verbose_name': 'دسته',
                'verbose_name_plural': 'دسته ها',
            },
        ),
    ]
