# Generated by Django 4.2.7 on 2023-11-23 16:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django_jalali.db.models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('store', '0002_remove_brand_name_remove_category_name_brand_name_en_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_fa', models.TextField(max_length=255, verbose_name='نام فارسی')),
                ('name_en', models.TextField(max_length=255, verbose_name='نام انگلیسی')),
                ('slug_name', models.SlugField(allow_unicode=True, blank=True, editable=False, max_length=255, null=True)),
                ('description', models.TextField(blank=True, max_length=1000, null=True, verbose_name='توضیحات')),
                ('seller_link', models.CharField(blank=True, max_length=1000, null=True, verbose_name='لینک فروشنده')),
                ('image_link', models.CharField(blank=True, max_length=1000, null=True, verbose_name='لینک تصویر محصول')),
                ('weight', models.CharField(blank=True, max_length=255, null=True, verbose_name='وزن')),
                ('brand', models.CharField(blank=True, max_length=255, null=True, verbose_name='برند')),
                ('price_uae', models.FloatField(blank=True, default=0, null=True, verbose_name='قیمت محصول به درهم')),
                ('price_toman', models.FloatField(blank=True, default=0, null=True, verbose_name='قیمت محصول به تومان')),
                ('batobox_fee', models.FloatField(blank=True, default=0, null=True, verbose_name='کارمزد باتوباکس')),
                ('batobox_delivery', models.FloatField(blank=True, default=0, null=True, verbose_name='هزینه جابجایی باتوباکس')),
                ('delivery_price', models.FloatField(blank=True, default=0, null=True, verbose_name='هزینه جابجایی آمازون')),
                ('final_price', models.FloatField(blank=True, default=0, null=True, verbose_name='هزینه نهایی محصول')),
                ('created_at', django_jalali.db.models.jDateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('updated_at', django_jalali.db.models.jDateTimeField(auto_now_add=True, verbose_name='تاریخ بروزرسانی')),
                ('created_by', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='product_created_by', to=settings.AUTH_USER_MODEL, verbose_name='کاربر ثبت کننده')),
                ('updated_by', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='product_updated_by', to=settings.AUTH_USER_MODEL, verbose_name='کاربر بروز کننده')),
            ],
            options={
                'verbose_name': 'محصول',
                'verbose_name_plural': 'محصولات',
            },
        ),
        migrations.CreateModel(
            name='ProductDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('special_home_product', models.BooleanField(default=False, verbose_name='نمایش محصول در صفحه خانه')),
                ('special_product', models.BooleanField(default=False, verbose_name='نمایش محصول در سایت')),
                ('link', models.TextField(blank=True, max_length=1000, null=True, verbose_name='لینک')),
                ('status', models.BooleanField(default=True)),
                ('customer_review_count', models.CharField(blank=True, max_length=512, null=True, verbose_name='تعداد نظرات محصول')),
                ('customer_review_score', models.CharField(blank=True, max_length=512, null=True, verbose_name='میانگین امتیاز محصول')),
                ('seo_title', models.CharField(blank=True, max_length=255, null=True, verbose_name='سئو - عنوان')),
                ('seo_keywords', models.CharField(blank=True, max_length=255, null=True, verbose_name='سئو - کلمات کلیدی')),
                ('seo_description', models.CharField(blank=True, max_length=255, null=True, verbose_name='سئو - توضیحات')),
                ('categories', models.ManyToManyField(blank=True, to='store.category', verbose_name='دسته ها')),
                ('product', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='product_detail_product', to='store.product', verbose_name='محصول')),
            ],
            options={
                'verbose_name': 'جزئیات محصول',
                'verbose_name_plural': 'جزئیات محصولات',
            },
        ),
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(blank=True, null=True, verbose_name='توضیحات کاربر')),
                ('status', models.IntegerField(choices=[(1, 'در حال بررسی'), (2, 'پرداخت شده و در انتظار بررسی'), (3, 'در انتظار پرداخت مبلغ اصلاحیه'), (4, 'درحال آماده سازی'), (5, 'ارسال شده'), (6, 'لغو شده'), (7, 'ارسال به ایران'), (8, 'در گمرک'), (9, 'در انبار باتوباکس')], default=1, verbose_name='وضعیت سفارش')),
                ('is_paid', models.BooleanField(default=False, verbose_name='پرداخت شده')),
                ('authority', models.CharField(blank=True, max_length=255, null=True)),
                ('ref_id', models.CharField(blank=True, max_length=255, null=True)),
                ('card_pan', models.CharField(blank=True, max_length=255, null=True)),
                ('card_hash', models.CharField(blank=True, max_length=255, null=True)),
                ('pay_amount', models.CharField(blank=True, max_length=255, null=True, verbose_name='قیمت کل سفارش')),
                ('fee_type', models.CharField(blank=True, max_length=255, null=True)),
                ('pay_fee', models.CharField(blank=True, max_length=255, null=True)),
                ('created_at', django_jalali.db.models.jDateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('updated_at', django_jalali.db.models.jDateTimeField(auto_now_add=True, verbose_name='تاریخ بروزرسانی')),
                ('created_by', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='cart_created_by', to=settings.AUTH_USER_MODEL, verbose_name='کاربر ثبت کننده')),
                ('products', models.ManyToManyField(related_name='products_cart', to='store.product', verbose_name='محصولات')),
                ('updated_by', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='cart_updated_by', to=settings.AUTH_USER_MODEL, verbose_name='کاربر بروز کننده')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_cart', to=settings.AUTH_USER_MODEL, verbose_name='کاربر')),
            ],
            options={
                'verbose_name': 'سفارش',
                'verbose_name_plural': 'سفارشات',
            },
        ),
    ]
