# Generated by Django 4.2.7 on 2023-11-30 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0004_batoboxcommission_currency_keyword_delete_brand_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='currency',
            name='currency_equivalent_price_in_toman',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='قیمت پایه واحد ارز به تومان'),
        ),
        migrations.AlterField(
            model_name='currency',
            name='exchange_fee_percentage',
            field=models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='درصد کارمزد تبدیل'),
        ),
        migrations.AlterField(
            model_name='currency',
            name='price_in_toman',
            field=models.PositiveIntegerField(blank=True, editable=False, null=True, verbose_name='قیمت نهایی واحد ارز به تومان'),
        ),
    ]
