# Generated by Django 4.2.7 on 2023-11-30 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0005_alter_currency_currency_equivalent_price_in_toman_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='توضیحات'),
        ),
        migrations.AlterField(
            model_name='product',
            name='final_price_in_toman',
            field=models.FloatField(blank=True, null=True, verbose_name='هزینه نهایی محصول با در نظر گیری کارمزد باتوباکس'),
        ),
    ]
