# Generated by Django 4.2.7 on 2023-12-01 12:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0009_alter_batoboxcommission_maximum_shipping_price_in_toman_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='requestedproduct',
            name='asin',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='asin'),
        ),
        migrations.AlterField(
            model_name='requestedproduct',
            name='currency',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='نماد ارز'),
        ),
        migrations.AlterField(
            model_name='requestedproduct',
            name='link',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='لینک'),
        ),
        migrations.AlterField(
            model_name='requestedproduct',
            name='price',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='قیمت'),
        ),
        migrations.AlterField(
            model_name='requestedproduct',
            name='weight',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='وزن به گرم'),
        ),
    ]
