# Generated by Django 4.2.7 on 2023-12-04 14:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django_jalali.db.models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('store', '0012_remove_requestedproduct_asin_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='RainForestApiAccessHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('api_query_result', models.TextField(editable=False, max_length=255, verbose_name='نتیجه درخواست')),
                ('created_at', django_jalali.db.models.jDateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('created_by', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='ایجاد شده توسط')),
            ],
            options={
                'verbose_name': 'سابقه دسترسی به محاسبه گر محصولات',
                'verbose_name_plural': 'سوابق دسترسی به محاسبه گر محصولات',
                'ordering': ['-created_at'],
            },
        ),
    ]
