# Generated by Django 4.2.7 on 2023-12-12 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0014_alter_rainforestapiaccesshistory_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='requestedproduct',
            name='amazon_related_product',
        ),
        migrations.RemoveField(
            model_name='requestedproduct',
            name='batobox_commission_percentage',
        ),
        migrations.RemoveField(
            model_name='requestedproduct',
            name='batobox_currency_exchange_fee_percentage',
        ),
        migrations.RemoveField(
            model_name='requestedproduct',
            name='batobox_shipping_price_in_toman',
        ),
        migrations.RemoveField(
            model_name='requestedproduct',
            name='price',
        ),
        migrations.AddField(
            model_name='requestedproduct',
            name='batobox_product_price',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='قیمت محصول به واحد ارز'),
        ),
        migrations.AddField(
            model_name='requestedproduct',
            name='batobox_shipping_price',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='قیمت حمل و نقل به واحد ارز'),
        ),
        migrations.AddField(
            model_name='requestedproduct',
            name='strict_currency_unit_related_price_in_tomans',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='وزن به گرم'),
        ),
    ]
