# Generated by Django 4.2.7 on 2023-12-12 15:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0015_remove_requestedproduct_amazon_related_product_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='BatoboxShipping',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('weight_from', models.PositiveIntegerField(verbose_name='وزن از (واحد گرم)')),
                ('weight_to', models.PositiveIntegerField(verbose_name='وزن تا (واحد گرم)')),
                ('price', models.PositiveIntegerField(verbose_name='مبلغ به واحد ارز')),
                ('currency', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store.currency', verbose_name='هزینه حمل مرتبط به ارز با نماد')),
            ],
            options={
                'verbose_name': 'هزینه حمل و نقل باتوباکس',
                'verbose_name_plural': 'هزینه های حمل و نقل باتوباکس',
            },
        ),
    ]
