# Generated by Django 4.2.7 on 2023-12-14 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0016_batoboxshipping'),
    ]

    operations = [
        migrations.CreateModel(
            name='BatoboxCurrencyExchangeCommission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('currency', models.CharField(max_length=255, verbose_name='کمیسون مرتبط به ارز با نماد')),
                ('price_from', models.PositiveIntegerField(verbose_name='قیمت از')),
                ('price_to', models.PositiveIntegerField(verbose_name='قیمت تا')),
                ('exchange_percentage', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='درصد کارمزد تبدیل')),
            ],
            options={
                'verbose_name': 'کارمزد تبدیل ارز باتوباکس',
                'verbose_name_plural': 'کارمزد های تبدیل ارز باتوباکس',
            },
        ),
        migrations.DeleteModel(
            name='BatoboxCommission',
        ),
        migrations.RemoveField(
            model_name='currency',
            name='exchange_fee_percentage',
        ),
        migrations.RemoveField(
            model_name='currency',
            name='price_in_toman',
        ),
    ]
