# Generated by Django 4.2.7 on 2023-12-17 14:32

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0017_batoboxcurrencyexchangecommission_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='batoboxcurrencyexchangecommission',
            name='unique_code',
            field=models.CharField(default=uuid.UUID('60610de0-be77-4518-bf47-450fd8b66615'), editable=False, max_length=255, verbose_name='کد یکتا'),
        ),
        migrations.AddField(
            model_name='batoboxshipping',
            name='unique_code',
            field=models.CharField(default=uuid.UUID('506c7ab8-d561-456b-986f-528edd335eb7'), editable=False, max_length=255, verbose_name='کد یکتا'),
        ),
        migrations.AddField(
            model_name='currency',
            name='is_active',
            field=models.BooleanField(default=False, verbose_name='فعال'),
        ),
        migrations.AddField(
            model_name='currency',
            name='unique_code',
            field=models.CharField(default=uuid.UUID('c61c29cb-99bf-4245-90cb-f3abda9eaa02'), editable=False, max_length=255, verbose_name='کد یکتا'),
        ),
        migrations.AlterField(
            model_name='batoboxcurrencyexchangecommission',
            name='currency',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store.currency', verbose_name='کمیسون مرتبط به ارز با نماد'),
        ),
        migrations.AlterField(
            model_name='batoboxcurrencyexchangecommission',
            name='exchange_percentage',
            field=models.PositiveSmallIntegerField(default=1, verbose_name='درصد کارمزد تبدیل'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='currency',
            name='currency_equivalent_price_in_toman',
            field=models.PositiveIntegerField(default=1, verbose_name='قیمت پایه واحد ارز به تومان'),
            preserve_default=False,
        ),
    ]
