# Generated by Django 4.2.7 on 2023-12-17 19:31

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0019_alter_batoboxcurrencyexchangecommission_unique_code_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='requestedproduct',
            name='batobox_final_price_in_toman',
        ),
        migrations.RemoveField(
            model_name='requestedproduct',
            name='batobox_product_price',
        ),
        migrations.RemoveField(
            model_name='requestedproduct',
            name='strict_currency_unit_related_price_in_tomans',
        ),
        migrations.AddField(
            model_name='requestedproduct',
            name='currency_exchange_percentage',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='درصد کمیسیون تبدیل ارز'),
        ),
        migrations.AddField(
            model_name='requestedproduct',
            name='final_price',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='قیمت نهایی به واحد ارز'),
        ),
        migrations.AddField(
            model_name='requestedproduct',
            name='final_price_in_toman',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='قیمت نهایی به تومان'),
        ),
        migrations.AddField(
            model_name='requestedproduct',
            name='product_price',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='قیمت محصول به واحد ارز'),
        ),
        migrations.AlterField(
            model_name='batoboxcurrencyexchangecommission',
            name='unique_code',
            field=models.CharField(default=uuid.UUID('7d5846a9-6729-4c3e-b01b-546c7c86fe7b'), editable=False, max_length=255, verbose_name='کد یکتا'),
        ),
        migrations.AlterField(
            model_name='batoboxshipping',
            name='unique_code',
            field=models.CharField(default=uuid.UUID('264178fe-6b35-4f80-9cd5-4f3c1117d4c6'), editable=False, max_length=255, verbose_name='کد یکتا'),
        ),
        migrations.AlterField(
            model_name='currency',
            name='unique_code',
            field=models.CharField(default=uuid.UUID('2753a730-116b-4d4c-91f9-c810d9ce744e'), editable=False, max_length=255, verbose_name='کد یکتا'),
        ),
    ]
