# Generated by Django 4.2.7 on 2023-12-17 19:39

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0020_remove_requestedproduct_batobox_final_price_in_toman_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='requestedproduct',
            name='batobox_currency_exchange_commission',
            field=models.TextField(blank=True, null=True, verbose_name='اطلاعات کمیسیون'),
        ),
        migrations.AddField(
            model_name='requestedproduct',
            name='batobox_shipping',
            field=models.TextField(blank=True, null=True, verbose_name='اطلاعات حمل و نقل'),
        ),
        migrations.AlterField(
            model_name='batoboxcurrencyexchangecommission',
            name='unique_code',
            field=models.CharField(default=uuid.UUID('d75a072f-187d-49a2-b78a-a7cbabc1ebca'), editable=False, max_length=255, verbose_name='کد یکتا'),
        ),
        migrations.AlterField(
            model_name='batoboxshipping',
            name='unique_code',
            field=models.CharField(default=uuid.UUID('a5d166ec-d855-48b1-9416-c88afa5b2b37'), editable=False, max_length=255, verbose_name='کد یکتا'),
        ),
        migrations.AlterField(
            model_name='currency',
            name='unique_code',
            field=models.CharField(default=uuid.UUID('df3a4cf4-f8df-4992-a1b1-bfe79d2ed1f6'), editable=False, max_length=255, verbose_name='کد یکتا'),
        ),
        migrations.AlterField(
            model_name='requestedproduct',
            name='currency',
            field=models.TextField(blank=True, null=True, verbose_name='اطلاعات ارز'),
        ),
    ]
