# Generated by Django 4.2.7 on 2024-01-02 12:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0022_requestedproduct_currency_equivalent_price_in_toman_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='requestedproduct',
            name='numbers',
            field=models.PositiveSmallIntegerField(blank=True, default=0, null=True, verbose_name='تعداد'),
        ),
    ]
