# Generated by Django 4.2.7 on 2024-01-31 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0024_requestedproduct_updated_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='requestedproduct',
            name='final_price_in_toman',
        ),
        migrations.AddField(
            model_name='requestedproduct',
            name='final_price_in_toman_multiple',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='قیمت نهایی محصول با احتساب تعداد به تومان'),
        ),
        migrations.AddField(
            model_name='requestedproduct',
            name='final_price_in_toman_single',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='قیمت نهایی تک محصول به تومان'),
        ),
        migrations.AddField(
            model_name='requestedproduct',
            name='request_status',
            field=models.CharField(choices=[('در حال بررسی', 'در حال بررسی'), ('پرداخت شده و در انتظار بررسی', 'پرداخت شده و در انتظار بررسی'), ('در انتظار پرداخت مبلغ اصلاحیه', 'در انتظار پرداخت مبلغ اصلاحیه'), ('دریافت سفارش', 'دریافت سفارش'), ('ثبت سفارش در سایت خارجی', 'ثبت سفارش در سایت خارجی'), ('در واحد خارج از کشور', 'در واحد خارج از کشور'), ('ارسال به ایران', 'ارسال به ایران'), ('در گمرک', 'در گمرک'), ('در انبار باتوباکس', 'در انبار باتوباکس'), ('ارسال شده', 'ارسال شده'), ('تکمیل شده', 'تکمیل شده'), ('لغو شده', 'لغو شده')], default='در حال بررسی', max_length=255, verbose_name='وضعیت سفارش'),
        ),
    ]
