# Generated by Django 4.2.7 on 2024-01-31 15:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0025_remove_requestedproduct_final_price_in_toman_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='requestedproduct',
            name='final_price',
        ),
    ]
