# Generated by Django 4.2.7 on 2023-12-28 15:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('custom_logs', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='customlog',
            options={'ordering': ['-created_at'], 'verbose_name': 'لاگ', 'verbose_name_plural': 'لاگ ها'},
        ),
    ]
