# Generated by Django 4.2.7 on 2023-11-23 12:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BannerMiddleFooter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('link', models.CharField(max_length=1000, verbose_name='لینک')),
                ('image', models.ImageField(upload_to='website/banner-middle-footer/', verbose_name='تصویر')),
            ],
            options={
                'verbose_name': 'بنر میانه صفحه',
                'verbose_name_plural': 'بنر های میانه صفحه',
            },
        ),
        migrations.CreateModel(
            name='BannerTopFooter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('link', models.CharField(max_length=1000, verbose_name='لینک')),
                ('image', models.ImageField(upload_to='website/banner-top-footer/', verbose_name='تصویر')),
            ],
            options={
                'verbose_name': 'بنر بالای فوتر',
                'verbose_name_plural': 'بنر های بالای فوتر',
            },
        ),
        migrations.CreateModel(
            name='BannerTopHeader',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='عنوان')),
                ('link', models.CharField(blank=True, max_length=1000, null=True, verbose_name='لینک')),
                ('link_text', models.CharField(blank=True, max_length=255, null=True, verbose_name='متن لینک')),
                ('image', models.ImageField(upload_to='website/banner-top-header/', verbose_name='تصویر')),
                ('title_color', models.CharField(choices=[('light', 'light'), ('dark', 'dark')], default='light', max_length=255, verbose_name='نوع رنگبندی عنوان')),
                ('btn_text_color', models.CharField(choices=[('light', 'light'), ('dark', 'dark')], default='light', max_length=255, verbose_name='نوع رنگبندی متن دکمه')),
                ('btn_color', models.CharField(choices=[('light', 'light'), ('dark', 'dark')], default='light', max_length=255, verbose_name='نوع رنگبندی دکمه')),
            ],
            options={
                'verbose_name': 'بنر بالای هدر',
                'verbose_name_plural': 'بنر های بالای هدر',
            },
        ),
        migrations.CreateModel(
            name='Currency',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('currency', models.CharField(max_length=255, verbose_name='نام')),
                ('currency_price_in_toman', models.FloatField(blank=True, null=True, verbose_name='قیمت ارز به تومان')),
                ('exchange_fee_percentage', models.FloatField(blank=True, null=True, verbose_name='درصد کارمزد تبدیل')),
                ('exchange_fee_min_price', models.FloatField(blank=True, null=True, verbose_name='کمترین قیمت تبدیل')),
                ('exchange_fee_max_price', models.FloatField(blank=True, null=True, verbose_name='بیشترین قیمت تبدیل')),
            ],
            options={
                'verbose_name': 'ارز',
                'verbose_name_plural': 'ارز ها',
            },
        ),
        migrations.CreateModel(
            name='FrequentlyAskedQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(max_length=255, verbose_name='سوال')),
                ('answer', models.TextField(verbose_name='جواب')),
            ],
            options={
                'verbose_name': 'سوال',
                'verbose_name_plural': 'سوالات متداول',
            },
        ),
        migrations.CreateModel(
            name='HomePageSlider',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='عنوان')),
                ('sub_title', models.CharField(max_length=255, verbose_name='زیر عنوان')),
                ('description', models.CharField(max_length=255, verbose_name='توضیحات')),
                ('link', models.CharField(max_length=1000, verbose_name='لینک')),
                ('link_text', models.CharField(blank=True, max_length=255, null=True, verbose_name='متن لینک')),
                ('image_desktop', models.ImageField(upload_to='website/home-page-slider-desktop/', verbose_name='تصویر دسکتاپ')),
                ('image_tablet', models.ImageField(upload_to='website/home-page-slider-tablet/', verbose_name='تصویر تبلت')),
                ('image_mobile', models.ImageField(upload_to='website/home-page-slider-mobile/', verbose_name='تصویر موبایل')),
            ],
            options={
                'verbose_name': 'اسلاید',
                'verbose_name_plural': 'اسلایدر خانه',
            },
        ),
        migrations.CreateModel(
            name='PageSeo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('page', models.CharField(choices=[('صفحه اصلی', 'صفحه اصلی'), ('تماس با ما', 'تماس با ما'), ('درباره ما', 'درباره ما'), ('سوالات متداول', 'سوالات متداول'), ('سبد خرید', 'سبد خرید'), ('پرداخت', 'پرداخت'), ('ماشین حساب امارات', 'ماشین حساب امارات'), ('ماشین حساب ترکیه', 'ماشین حساب ترکیه'), ('قوانین ما', 'قوانین ما')], max_length=255, verbose_name='صفحه')),
                ('title', models.CharField(max_length=255, verbose_name='عنوان')),
                ('keywords', models.CharField(max_length=255, verbose_name='کلمات کلیدی')),
                ('description', models.CharField(max_length=255, verbose_name='توضیحات')),
                ('canonical', models.CharField(max_length=1000, verbose_name='کنونیکال')),
                ('robots', models.CharField(choices=[('index, follow', 'index, follow'), ('noindex, nofollow', 'noindex, nofollow'), ('index', 'index'), ('follow', 'follow'), ('noindex', 'noindex'), ('nofollow', 'nofollow'), ('index, nofollow', 'index, nofollow'), ('noindex, follow', 'noindex, follow')], max_length=255, verbose_name='عملکرد ربات')),
                ('page_type', models.CharField(choices=[('website', 'website'), ('article', 'article'), ('blog', 'blog'), ('book', 'book'), ('game', 'game'), ('film', 'film'), ('food', 'food'), ('city', 'city'), ('country', 'country'), ('actor', 'actor'), ('author', 'author'), ('politician', 'politician'), ('company', 'company'), ('hotel', 'hotel'), ('restaurant', 'restaurant')], max_length=255, verbose_name='نوع صفحه')),
                ('image', models.ImageField(upload_to='website/page-seo-tool/')),
            ],
            options={
                'verbose_name': 'سئو صفحه',
                'verbose_name_plural': 'سئو صفحات',
            },
        ),
        migrations.CreateModel(
            name='TermAndCondition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('law', models.CharField(max_length=255, verbose_name='قانون')),
                ('law_description', models.TextField(verbose_name='توضیحات قانون')),
            ],
            options={
                'verbose_name': 'شرط و قانون',
                'verbose_name_plural': 'شرایط و قوانین',
            },
        ),
        migrations.CreateModel(
            name='WhyUsReason',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reason', models.CharField(max_length=255, verbose_name='دلیل')),
                ('description', models.TextField(verbose_name='توضیحات')),
                ('image', models.ImageField(blank=True, null=True, upload_to='website/home-page-shipping/')),
            ],
            options={
                'verbose_name': 'دلیل خرید از ما',
                'verbose_name_plural': 'دلایل خرید از ما',
            },
        ),
        migrations.CreateModel(
            name='TransportCost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('weight', models.FloatField(verbose_name='وزن به کیلوگرم')),
                ('price', models.FloatField(verbose_name='مبلغ بر اساس ارز')),
                ('currency', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='currency_from_transport_cost', to='website.currency', verbose_name='ارز')),
            ],
            options={
                'verbose_name': 'هزینه حمل',
                'verbose_name_plural': 'هزینه های حمل',
            },
        ),
    ]
