# Generated by Django 4.2.7 on 2023-11-23 12:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transportcost',
            name='weight',
        ),
        migrations.AddField(
            model_name='transportcost',
            name='weight_from',
            field=models.FloatField(default=1, verbose_name='وزن از (واحد گرم)'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='transportcost',
            name='weight_to',
            field=models.FloatField(default=1, verbose_name='وزن تا (واحد گرم)'),
            preserve_default=False,
        ),
    ]
