# Generated by Django 4.2.7 on 2023-12-01 12:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0003_remove_transportcost_currency_delete_currency_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Websites',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('site_type', models.CharField(choices=[('turkey', 'ترکیه'), ('emirates', 'امارات')], max_length=255, verbose_name='نوع سایت')),
                ('title', models.CharField(blank=True, max_length=255, null=True, verbose_name='عنوان')),
                ('description', models.CharField(blank=True, max_length=1000, null=True, verbose_name='توضیحات')),
                ('image', models.ImageField(blank=True, null=True, upload_to='website/', verbose_name='تصویر')),
                ('link', models.CharField(blank=True, max_length=1000, null=True, verbose_name='لینک')),
            ],
            options={
                'verbose_name': 'سایت',
                'verbose_name_plural': 'سایت ها',
            },
        ),
    ]
