# Generated by Django 4.2.7 on 2023-12-14 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0004_websites'),
    ]

    operations = [
        migrations.CreateModel(
            name='DynamicData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=255, verbose_name='کلید')),
                ('value', models.TextField(verbose_name='مقدار')),
            ],
            options={
                'verbose_name': 'dynamic data',
                'verbose_name_plural': 'dynamic data',
            },
        ),
        migrations.RenameModel(
            old_name='Websites',
            new_name='Website',
        ),
    ]
