# Generated by Django 4.2.7 on 2023-12-17 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0005_dynamicdata_rename_websites_website'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='dynamicdata',
            options={'verbose_name': 'داینامیک دیتا', 'verbose_name_plural': 'داینامیک دیتا'},
        ),
        migrations.AlterField(
            model_name='bannertopheader',
            name='link_text',
            field=models.CharField(default=1, max_length=255, verbose_name='متن لینک'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='homepageslider',
            name='link_text',
            field=models.CharField(default=1, max_length=255, verbose_name='متن لینک'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='pageseo',
            name='image',
            field=models.ImageField(upload_to='website/page-seo-tool/', verbose_name='تصویر صفحه'),
        ),
        migrations.AlterField(
            model_name='website',
            name='description',
            field=models.CharField(default=1, max_length=1000, verbose_name='توضیحات'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='website',
            name='image',
            field=models.ImageField(default=1, upload_to='website/', verbose_name='تصویر'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='website',
            name='link',
            field=models.CharField(default=1, max_length=1000, verbose_name='لینک'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='website',
            name='title',
            field=models.CharField(default=1, max_length=255, verbose_name='عنوان'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='whyusreason',
            name='image',
            field=models.ImageField(default=1, upload_to='website/why-us-reason/'),
            preserve_default=False,
        ),
    ]
