# Generated by Django 4.2.7 on 2023-11-19 08:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django_jalali.db.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SMSAuthCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone_number', models.CharField(editable=False, max_length=255, verbose_name='شماره موبایل')),
                ('pass_code', models.CharField(editable=False, max_length=255, verbose_name='کد احراز')),
                ('created_at', django_jalali.db.models.jDateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
            ],
            options={
                'verbose_name': 'کد تایید پیامکی',
                'verbose_name_plural': 'کد های تایید پیامکی',
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='Websites',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('site_type', models.CharField(choices=[('turkey', 'ترکیه'), ('emirates', 'امارات')], max_length=255, verbose_name='نوع سایت')),
                ('title', models.CharField(blank=True, max_length=255, null=True, verbose_name='عنوان')),
                ('description', models.CharField(blank=True, max_length=1000, null=True, verbose_name='توضیحات')),
                ('image', models.ImageField(blank=True, null=True, upload_to='website/', verbose_name='تصویر')),
                ('link', models.CharField(blank=True, max_length=1000, null=True, verbose_name='لینک')),
            ],
            options={
                'verbose_name': 'سایت',
                'verbose_name_plural': 'سایت ها',
            },
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_type', models.CharField(choices=[('deposit', 'افزایش موجودی کیف پول'), ('withdraw', 'برداشت از کیف پول')], default='deposit', max_length=255, verbose_name='نوع تراکنش')),
                ('transaction_status', models.CharField(choices=[('pending', 'در حال بررسی'), ('done', 'انجام شده'), ('denied', 'رد شده')], default='pending', max_length=255, verbose_name='وضعیت تراکنش')),
                ('price_change_in_wallet', models.BooleanField(default=False)),
                ('wallet_before', models.CharField(blank=True, help_text='این فیلد خودکار پر میشود', max_length=255, null=True)),
                ('wallet_after', models.CharField(blank=True, help_text='این فیلد خودکار پر میشود', max_length=255, null=True)),
                ('authority', models.CharField(blank=True, max_length=255, null=True)),
                ('ref_id', models.CharField(blank=True, max_length=255, null=True)),
                ('card_pan', models.CharField(blank=True, max_length=255, null=True)),
                ('card_hash', models.CharField(blank=True, max_length=255, null=True)),
                ('pay_amount', models.CharField(blank=True, max_length=255, null=True, verbose_name='مبلغ تراکنش - تومان')),
                ('fee_type', models.CharField(blank=True, max_length=255, null=True)),
                ('pay_fee', models.CharField(blank=True, max_length=255, null=True)),
                ('created_at', django_jalali.db.models.jDateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('updated_at', django_jalali.db.models.jDateTimeField(auto_now=True, verbose_name='تاریخ بروز رسانی')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_ticket', to=settings.AUTH_USER_MODEL, verbose_name='کاربر')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_transactions', to=settings.AUTH_USER_MODEL, verbose_name='کاربر')),
            ],
            options={
                'verbose_name': 'تراکنش کاربر',
                'verbose_name_plural': 'تراکنش های کاربران',
            },
        ),
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', 'در حال بررسی'), ('answered', 'پاسخ داده شده'), ('closed', 'بسته شده')], default='pending', max_length=255, verbose_name='وضعیت')),
                ('title', models.CharField(blank=True, max_length=512, null=True, verbose_name='عنوان تیکت')),
                ('description', models.TextField(blank=True, null=True, verbose_name='توضیحات تیکت')),
                ('created_at', django_jalali.db.models.jDateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('updated_at', django_jalali.db.models.jDateTimeField(auto_now=True, verbose_name='تاریخ بروز رسانی')),
                ('created_by', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='created_by_ticket', to=settings.AUTH_USER_MODEL, verbose_name='ساخته شده توسط')),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='creator_ticket', to=settings.AUTH_USER_MODEL, verbose_name='سازنده تیکت')),
                ('updated_by', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='updated_by_ticket', to=settings.AUTH_USER_MODEL, verbose_name='بروز شده توسط')),
            ],
            options={
                'verbose_name': 'تیکت',
                'verbose_name_plural': 'تیکت ها',
            },
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profile_pic', models.ImageField(blank=True, null=True, upload_to='', verbose_name='عکس پروفایل')),
                ('mobile_phone_number', models.CharField(blank=True, max_length=255, null=True, verbose_name='شماره همراه')),
                ('landline', models.CharField(blank=True, max_length=255, null=True, verbose_name='شماره ثابت')),
                ('email', models.CharField(blank=True, max_length=255, null=True, verbose_name='ایمیل')),
                ('birthday', django_jalali.db.models.jDateField(blank=True, null=True, verbose_name='تاریخ تولد')),
                ('province', models.CharField(blank=True, max_length=255, null=True, verbose_name='ایالت')),
                ('city', models.CharField(blank=True, max_length=255, null=True, verbose_name='شهر')),
                ('address', models.CharField(blank=True, max_length=255, null=True, verbose_name='آدرس')),
                ('zip_code', models.CharField(blank=True, max_length=255, null=True, verbose_name='کد پستی')),
                ('verification', models.BooleanField(default=False, editable=False, verbose_name='تاییدیه')),
                ('token', models.CharField(blank=True, editable=False, max_length=255, null=True, verbose_name='توکن')),
                ('number_of_send_sms', models.PositiveSmallIntegerField(default=0, editable=False, verbose_name='تعداد sms های ارسالی')),
                ('wallet_balance', models.PositiveIntegerField(default=0, verbose_name='اعتبار کیف پول')),
                ('created_at', django_jalali.db.models.jDateTimeField(auto_now_add=True, verbose_name='عضویت در تاریخ')),
                ('user', models.OneToOneField(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='user_profile', to=settings.AUTH_USER_MODEL, verbose_name='کاربر')),
            ],
            options={
                'verbose_name': 'پروفایل کاربر',
                'verbose_name_plural': 'پروفایل های کاربران',
            },
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(verbose_name='محتوا')),
                ('status', models.CharField(choices=[('sent', 'ارسال شده'), ('seen', 'دیده شده'), ('deleted', 'حذف شده')], max_length=255, verbose_name='وضعیت پیام')),
                ('created_at', django_jalali.db.models.jDateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('updated_at', django_jalali.db.models.jDateTimeField(auto_now=True, verbose_name='تاریخ بروز رسانی')),
                ('created_by', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='created_by_message', to=settings.AUTH_USER_MODEL, verbose_name='ساخته شده توسط')),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='creator_message', to=settings.AUTH_USER_MODEL, verbose_name='سازنده پیام')),
                ('ticket', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ticket_message', to='accounts.ticket', verbose_name='تیکت')),
                ('updated_by', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='updated_by_message', to=settings.AUTH_USER_MODEL, verbose_name='بروز شده توسط')),
            ],
            options={
                'verbose_name': 'پیام',
                'verbose_name_plural': 'پیام ها',
            },
        ),
    ]
