# Generated by Django 4.2.7 on 2023-12-01 12:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django_jalali.db.models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0008_requestedproduct_remove_category_parent_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('accounts', '0003_alter_profile_options_alter_transaction_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='PermanentOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('products_details', models.TextField(editable=False, verbose_name='محصولات نهایی شده')),
                ('total_price', models.PositiveIntegerField(editable=False, verbose_name='مبلغ نهایی قابل پرداخت')),
                ('order_status', models.IntegerField(choices=[(1, 'در حال بررسی'), (2, 'پرداخت شده و در انتظار بررسی'), (3, 'در انتظار پرداخت مبلغ اصلاحیه'), (4, 'درحال آماده سازی'), (5, 'ارسال شده'), (6, 'لغو شده'), (7, 'ارسال به ایران'), (8, 'در گمرک'), (9, 'در انبار باتوباکس')], default=1, verbose_name='وضعیت سفارش')),
                ('is_paid', models.BooleanField(default=False, verbose_name='پرداخت شده')),
                ('updated_at', django_jalali.db.models.jDateTimeField(auto_now_add=True, verbose_name='تاریخ بروزرسانی')),
                ('user', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='user_permanent_order', to=settings.AUTH_USER_MODEL, verbose_name='کاربر')),
            ],
            options={
                'verbose_name': 'سبد نهایی',
                'verbose_name_plural': 'سبد های نهایی',
            },
        ),
        migrations.CreateModel(
            name='TemporaryCart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(blank=True, null=True, verbose_name='توضیحات کاربر')),
                ('created_at', django_jalali.db.models.jDateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('updated_at', django_jalali.db.models.jDateTimeField(auto_now_add=True, verbose_name='تاریخ بروزرسانی')),
                ('products', models.ManyToManyField(related_name='products_cart', to='store.requestedproduct', verbose_name='محصولات')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='user_temporary_cart', to=settings.AUTH_USER_MODEL, verbose_name='کاربر')),
            ],
            options={
                'verbose_name': 'سبد موقت',
                'verbose_name_plural': 'سبد های موقت',
            },
        ),
        migrations.CreateModel(
            name='TransactionHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_price', models.PositiveIntegerField()),
                ('transaction_type', models.CharField(choices=[('deposit', 'افزایش موجودی کیف پول'), ('withdraw', 'برداشت از کیف پول')], default='deposit', max_length=255, verbose_name='نوع تراکنش')),
                ('transaction_status', models.CharField(choices=[('pending', 'در حال بررسی'), ('done', 'انجام شده'), ('denied', 'رد شده')], default='pending', max_length=255, verbose_name='وضعیت تراکنش')),
                ('authority', models.CharField(blank=True, max_length=255, null=True)),
                ('ref_id', models.CharField(blank=True, max_length=255, null=True)),
                ('card_pan', models.CharField(blank=True, max_length=255, null=True)),
                ('card_hash', models.CharField(blank=True, max_length=255, null=True)),
                ('pay_amount', models.CharField(blank=True, max_length=255, null=True, verbose_name='مبلغ تراکنش - تومان')),
                ('created_at', django_jalali.db.models.jDateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('updated_at', django_jalali.db.models.jDateTimeField(auto_now=True, verbose_name='تاریخ بروز رسانی')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_transaction_history', to=settings.AUTH_USER_MODEL, verbose_name='کاربر')),
            ],
            options={
                'verbose_name': 'سابقه تراکنش',
                'verbose_name_plural': 'سوابق تراکنش',
            },
        ),
        migrations.RemoveField(
            model_name='message',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='message',
            name='creator',
        ),
        migrations.RemoveField(
            model_name='message',
            name='ticket',
        ),
        migrations.RemoveField(
            model_name='message',
            name='updated_by',
        ),
        migrations.RemoveField(
            model_name='ticket',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='ticket',
            name='creator',
        ),
        migrations.RemoveField(
            model_name='ticket',
            name='updated_by',
        ),
        migrations.RemoveField(
            model_name='transaction',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='transaction',
            name='user',
        ),
        migrations.DeleteModel(
            name='Websites',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='number_of_send_sms',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='token',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='verification',
        ),
        migrations.DeleteModel(
            name='Message',
        ),
        migrations.DeleteModel(
            name='Ticket',
        ),
        migrations.DeleteModel(
            name='Transaction',
        ),
    ]
