# Generated by Django 4.2.7 on 2023-12-01 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0009_alter_batoboxcommission_maximum_shipping_price_in_toman_and_more'),
        ('accounts', '0004_permanentorder_temporarycart_transactionhistory_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='temporarycart',
            name='description',
        ),
        migrations.AlterField(
            model_name='temporarycart',
            name='products',
            field=models.ManyToManyField(blank=True, related_name='temporary_card_products', to='store.requestedproduct', verbose_name='محصولات'),
        ),
    ]
