# Generated by Django 4.2.7 on 2023-12-11 09:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_remove_temporarycart_description_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='like_list',
            field=models.TextField(blank=True, null=True, verbose_name='لیست محصولات مورد علاقه'),
        ),
        migrations.AddField(
            model_name='profile',
            name='wish_list',
            field=models.TextField(blank=True, null=True, verbose_name='لیست خرید های احتمالی در آینده'),
        ),
    ]
