# Generated by Django 4.2.7 on 2023-12-11 09:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_profile_like_list_profile_wish_list'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='temp_card',
            field=models.TextField(blank=True, null=True, verbose_name='محصولات در سبد خرید'),
        ),
        migrations.DeleteModel(
            name='TemporaryCart',
        ),
    ]
