# Generated by Django 4.2.7 on 2023-12-11 11:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django_jalali.db.models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('accounts', '0008_order_delete_permanentorder'),
    ]

    operations = [
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.PositiveIntegerField(verbose_name='مبلغ - تومان')),
                ('description', models.TextField(blank=True, null=True, verbose_name='توضیحات')),
                ('email', models.TextField(blank=True, null=True, verbose_name='ایمیل')),
                ('mobile', models.TextField(blank=True, null=True, verbose_name='موبایل')),
                ('authority', models.CharField(blank=True, max_length=255, null=True)),
                ('ref_id', models.CharField(blank=True, max_length=255, null=True)),
                ('status', models.CharField(choices=[('pending', 'در حال بررسی'), ('done', 'انجام شده'), ('denied', 'رد شده')], default='pending', max_length=255, verbose_name='وضعیت')),
                ('created_at', django_jalali.db.models.jDateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('updated_at', django_jalali.db.models.jDateTimeField(auto_now=True, verbose_name='تاریخ بروز رسانی')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_transaction_history', to=settings.AUTH_USER_MODEL, verbose_name='کاربر')),
            ],
            options={
                'verbose_name': 'تراکنش',
                'verbose_name_plural': 'تراکنش ها',
            },
        ),
        migrations.DeleteModel(
            name='TransactionHistory',
        ),
    ]
