# Generated by Django 4.2.7 on 2023-12-18 09:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0022_requestedproduct_currency_equivalent_price_in_toman_and_more'),
        ('accounts', '0010_remove_profile_profile_pic'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='products_details',
        ),
        migrations.AddField(
            model_name='order',
            name='products',
            field=models.ManyToManyField(blank=True, to='store.requestedproduct', verbose_name='محصولات نهایی شده'),
        ),
    ]
