# Generated by Django 4.2.7 on 2023-12-19 09:50

import datetime
from django.db import migrations, models
import django_jalali.db.models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0013_remove_order_all_time_payed_amount_in_tomans_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='wallet_balance_allow_change_code',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='کد یکتای تغییر اعتبار حساب'),
        ),
        migrations.AddField(
            model_name='profile',
            name='wallet_balance_code_expiry_date',
            field=django_jalali.db.models.jDateTimeField(blank=True, default=datetime.datetime(2023, 12, 19, 9, 50, 23, 20394), null=True, verbose_name='اعتبار کد تغییر اعتبار حساب'),
        ),
    ]
