# Generated by Django 4.2.7 on 2023-12-25 15:03

import datetime
from django.db import migrations, models
import django_jalali.db.models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0014_profile_wallet_balance_allow_change_code_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='wallet_balance_code_expiry_date',
            field=django_jalali.db.models.jDateTimeField(blank=True, default=datetime.datetime(2023, 12, 25, 15, 3, 48, 485892), null=True, verbose_name='اعتبار کد تغییر اعتبار حساب'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='status',
            field=models.CharField(choices=[('پرداخت نشده', 'پرداخت نشده'), ('پرداخت شده', 'پرداخت شده')], default='pending', max_length=255, verbose_name='وضعیت'),
        ),
    ]
