# Generated by Django 4.2.7 on 2023-12-28 11:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('accounts', '0015_alter_profile_wallet_balance_code_expiry_date_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='wallet_balance_allow_change_code',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='wallet_balance_code_expiry_date',
        ),
        migrations.AlterField(
            model_name='order',
            name='order_status',
            field=models.IntegerField(choices=[('در حال بررسی', 'در حال بررسی'), ('پرداخت شده و در انتظار بررسی', 'پرداخت شده و در انتظار بررسی'), ('در انتظار پرداخت مبلغ اصلاحیه', 'در انتظار پرداخت مبلغ اصلاحیه'), ('درحال آماده سازی', 'درحال آماده سازی'), ('ارسال شده', 'ارسال شده'), ('لغو شده', 'لغو شده'), ('ارسال به ایران', 'ارسال به ایران'), ('در گمرک', 'در گمرک'), ('در انبار باتوباکس', 'در انبار باتوباکس'), ('تکمیل شده', 'تکمیل شده')], default=1, verbose_name='وضعیت سفارش'),
        ),
        migrations.CreateModel(
            name='WalletChangeCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unique_code', models.CharField(max_length=255, verbose_name='کد یکتا')),
                ('is_used', models.BooleanField(default=False, verbose_name='استفاده شده')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_wallet_change_code', to=settings.AUTH_USER_MODEL, verbose_name='کاربر')),
            ],
            options={
                'verbose_name': 'کد تغییر اعتبار حساب',
                'verbose_name_plural': 'کد های تغییر اعتبار حساب',
            },
        ),
    ]
