# Generated by Django 4.2.7 on 2023-12-28 13:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('accounts', '0016_remove_profile_wallet_balance_allow_change_code_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unique_code', models.CharField(max_length=255, verbose_name='کد یکتا')),
                ('is_used', models.BooleanField(default=False, verbose_name='استفاده شده')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_wallet_change_code', to=settings.AUTH_USER_MODEL, verbose_name='کاربر')),
            ],
            options={
                'verbose_name': 'کد پرداخت',
                'verbose_name_plural': 'کد های پرداخت',
            },
        ),
        migrations.DeleteModel(
            name='WalletChangeCode',
        ),
    ]
