# Generated by Django 4.2.7 on 2023-12-28 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0017_paymentcode_delete_walletchangecode'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='order_status',
            field=models.CharField(choices=[('در حال بررسی', 'در حال بررسی'), ('پرداخت شده و در انتظار بررسی', 'پرداخت شده و در انتظار بررسی'), ('در انتظار پرداخت مبلغ اصلاحیه', 'در انتظار پرداخت مبلغ اصلاحیه'), ('درحال آماده سازی', 'درحال آماده سازی'), ('ارسال شده', 'ارسال شده'), ('لغو شده', 'لغو شده'), ('ارسال به ایران', 'ارسال به ایران'), ('در گمرک', 'در گمرک'), ('در انبار باتوباکس', 'در انبار باتوباکس'), ('تکمیل شده', 'تکمیل شده')], default='در حال بررسی', max_length=255, verbose_name='وضعیت سفارش'),
        ),
    ]
