# Generated by Django 4.2.7 on 2023-12-28 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0018_alter_order_order_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='description',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='توضیحات'),
        ),
    ]
