# Generated by Django 4.2.7 on 2023-12-28 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0019_order_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='description',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='توضیحات'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='email',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='ایمیل'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='mobile',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='موبایل'),
        ),
    ]
