# Generated by Django 4.2.7 on 2024-01-04 18:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0022_remove_profile_mobile_phone_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='province',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='استان'),
        ),
    ]
