# Generated by Django 4.2.7 on 2024-01-07 10:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0023_alter_profile_province'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='address',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='city',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='province',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='zip_code',
        ),
        migrations.AddField(
            model_name='profile',
            name='card_number',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='شماره کارت'),
        ),
        migrations.AddField(
            model_name='profile',
            name='isbn',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='شماره شبا'),
        ),
        migrations.AddField(
            model_name='profile',
            name='national_code',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='کد ملی'),
        ),
        migrations.AddField(
            model_name='profile',
            name='receiver_details',
            field=models.TextField(blank=True, null=True, verbose_name='مشخصات ارسال'),
        ),
    ]
