# Generated by Django 4.2.7 on 2024-01-07 10:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0024_remove_profile_address_remove_profile_city_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='card_number',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='شماره کارت'),
        ),
        migrations.AddField(
            model_name='order',
            name='first_name',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='نام'),
        ),
        migrations.AddField(
            model_name='order',
            name='isbn',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='شماره شبا'),
        ),
        migrations.AddField(
            model_name='order',
            name='landline',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='شماره تماس ثابت'),
        ),
        migrations.AddField(
            model_name='order',
            name='last_name',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='نام خانوادگی'),
        ),
        migrations.AddField(
            model_name='order',
            name='mobile_phone_number',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='شماره تماس همراه'),
        ),
        migrations.AddField(
            model_name='order',
            name='national_code',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='کد ملی'),
        ),
        migrations.AddField(
            model_name='order',
            name='receiver_address',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='آدرس گیرنده'),
        ),
        migrations.AddField(
            model_name='order',
            name='receiver_city',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='شهر گیرنده'),
        ),
        migrations.AddField(
            model_name='order',
            name='receiver_mobile_phone_number',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='شماره تماس همراه گیرنده'),
        ),
        migrations.AddField(
            model_name='order',
            name='receiver_province',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='استان گیرنده'),
        ),
        migrations.AddField(
            model_name='order',
            name='receiver_zip_code',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='کد پستی گیرنده'),
        ),
    ]
