# Generated by Django 4.2.7 on 2024-01-07 11:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0025_order_card_number_order_first_name_order_isbn_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='receiver_details',
        ),
        migrations.AddField(
            model_name='profile',
            name='location_details',
            field=models.TextField(blank=True, null=True, verbose_name='مشخصات مکانی'),
        ),
    ]
