# Generated by Django 4.2.7 on 2023-11-30 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AmazonScraperSetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sleep_time', models.PositiveSmallIntegerField(default=5, verbose_name='زمان توقف ربات بین هر کوئری')),
                ('amazon_thread_number', models.PositiveSmallIntegerField(default=4, verbose_name='تعداد پردازش همزمان انواتو')),
                ('amazon_queue_number', models.PositiveSmallIntegerField(default=4, verbose_name='تعداد پردازش صف انواتو')),
            ],
            options={
                'verbose_name': 'تنظیمات اسکرپر آمازون',
                'verbose_name_plural': 'تنظیمات اسکرپر آمازون',
            },
        ),
    ]
