# Generated by Django 4.2.7 on 2023-11-30 14:59

from django.db import migrations, models
import django_jalali.db.models


class Migration(migrations.Migration):

    dependencies = [
        ('amazon', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='RainForestApiAccessHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source_ip', models.CharField(editable=False, max_length=255, verbose_name='آی پی')),
                ('asin', models.CharField(editable=False, max_length=255, verbose_name='asin درخواست شده')),
                ('created_at', django_jalali.db.models.jDateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
            ],
            options={
                'verbose_name': 'سابقه دسترسی به rainforest api',
                'verbose_name_plural': 'سوابق دسترسی به rainforest api',
            },
        ),
        migrations.DeleteModel(
            name='AmazonScraperSetting',
        ),
    ]
