# Generated by Django 4.2.7 on 2023-12-01 11:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django_jalali.db.models


class Migration(migrations.Migration):

    dependencies = [
        ('storage', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('amazon', '0003_rainforestapiaccesshistory_created_by'),
    ]

    operations = [
        migrations.CreateModel(
            name='AmazonProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('asin', models.CharField(max_length=255, verbose_name='ASIN')),
                ('amazon_product_root_domain', models.CharField(blank=True, max_length=1000, null=True, verbose_name='لینک کشور-محصول آمازون')),
                ('product_root_url', models.CharField(blank=True, max_length=1000, null=True, verbose_name='لینک ریشه محصول در آمازون')),
                ('product_main_url', models.CharField(blank=True, max_length=1000, null=True, verbose_name='لینک اصلی محصول در آمازون')),
                ('product_type', models.CharField(blank=True, max_length=255, null=True, verbose_name='نوع محصول')),
                ('title_fa', models.CharField(blank=True, max_length=255, null=True, verbose_name='عنوان فارسی')),
                ('title_en', models.CharField(blank=True, max_length=255, null=True, verbose_name='عنوان انگلیسی')),
                ('slug_title', models.SlugField(allow_unicode=True, blank=True, editable=False, max_length=255, null=True, verbose_name='اسلاگ عنوان')),
                ('description', models.TextField(blank=True, null=True, verbose_name='توضیحات')),
                ('brand', models.CharField(blank=True, max_length=255, null=True, verbose_name='برند')),
                ('product_brand_url', models.CharField(blank=True, max_length=1000, null=True, verbose_name='لینک برند محصول در آمازون')),
                ('user_rating_count', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='تعداد امتیاز دهندگان به محصول')),
                ('rating_score', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='امتیاز محصول')),
                ('main_image', models.ImageField(blank=True, null=True, upload_to='product-image/', verbose_name='تصویر اصلی محصول')),
                ('feature_bullets', models.TextField(blank=True, null=True, verbose_name='ویژگی های کلیدی')),
                ('attributes', models.TextField(blank=True, null=True, verbose_name='امکانات')),
                ('weight', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='وزن بر اساس گرم')),
                ('specifications', models.TextField(blank=True, null=True, verbose_name='مشخصات')),
                ('currency', models.CharField(blank=True, max_length=1000, null=True, verbose_name='ارز')),
                ('base_price', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='قیمت پایه')),
                ('shipping_price', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='قیمت پایه حمل و نقل از آمازون')),
                ('final_price_in_toman', models.FloatField(blank=True, null=True, verbose_name='هزینه نهایی محصول با در نظر گیری کارمزد باتوباکس')),
                ('is_product_available', models.BooleanField(default=True, verbose_name='محصول فعال')),
                ('is_product_special', models.BooleanField(default=False, verbose_name='محصول ویژه')),
                ('created_at', django_jalali.db.models.jDateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('updated_at', django_jalali.db.models.jDateTimeField(auto_now_add=True, verbose_name='تاریخ بروزرسانی')),
                ('get_new_details_from_rainforest_api', models.BooleanField(default=False, verbose_name='دریافت اطلاعات جدید از rainforest api')),
                ('created_by', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='amazon_product_created_by', to=settings.AUTH_USER_MODEL, verbose_name='کاربر ثبت کننده')),
                ('documents', models.ManyToManyField(blank=True, related_name='product_documents', to='storage.storage', verbose_name='مستندات')),
                ('images', models.ManyToManyField(blank=True, related_name='product_images', to='storage.storage', verbose_name='تصاویر')),
                ('updated_by', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='amazon_product_updated_by', to=settings.AUTH_USER_MODEL, verbose_name='کاربر بروز کننده')),
            ],
            options={
                'verbose_name': 'محصول',
                'verbose_name_plural': 'محصولات',
            },
        ),
    ]
