# Generated by Django 4.2.7 on 2023-12-01 12:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('amazon', '0004_amazonproduct'),
    ]

    operations = [
        migrations.CreateModel(
            name='Keyword',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title_fa', models.CharField(max_length=255, verbose_name='عنوان فارسی')),
                ('title_en', models.CharField(max_length=255, verbose_name='عنوان انگلیسی')),
                ('title_slug', models.SlugField(allow_unicode=True, blank=True, editable=False, max_length=255, null=True, verbose_name='اسلاگ عنوان')),
            ],
            options={
                'verbose_name': 'کلمه کلیدی',
                'verbose_name_plural': 'کلمات کلیدی',
            },
        ),
        migrations.AlterModelOptions(
            name='amazonproduct',
            options={'verbose_name': 'محصول آمازون', 'verbose_name_plural': 'محصولات'},
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('parent_tree', models.TextField(blank=True, editable=False, null=True, verbose_name='درخت رابطه')),
                ('title_fa', models.CharField(max_length=255, verbose_name='عنوان فارسی')),
                ('title_en', models.CharField(max_length=255, verbose_name='عنوان انگلیسی')),
                ('title_slug', models.SlugField(allow_unicode=True, blank=True, editable=False, max_length=255, null=True, verbose_name='اسلاگ عنوان')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='parent_category', to='amazon.category', verbose_name='دسته مادر')),
            ],
            options={
                'verbose_name': 'دسته',
                'verbose_name_plural': 'دسته ها',
            },
        ),
        migrations.AddField(
            model_name='amazonproduct',
            name='categories',
            field=models.ManyToManyField(blank=True, related_name='product_categories', to='amazon.category', verbose_name='دسته ها'),
        ),
        migrations.AddField(
            model_name='amazonproduct',
            name='keywords',
            field=models.ManyToManyField(blank=True, related_name='product_keywords', to='amazon.keyword', verbose_name='کلمات کلیدی'),
        ),
    ]
