# Generated by Django 4.2.7 on 2023-12-01 12:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('amazon', '0005_keyword_alter_amazonproduct_options_category_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='amazonproduct',
            options={'verbose_name': 'محصول آمازون', 'verbose_name_plural': 'محصولات آمازون'},
        ),
    ]
