# Generated by Django 4.2.7 on 2023-12-01 12:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('amazon', '0006_alter_amazonproduct_options'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='amazonproduct',
            name='final_price_in_toman',
        ),
        migrations.AddField(
            model_name='amazonproduct',
            name='total_price',
            field=models.FloatField(blank=True, null=True, verbose_name='قیمت نهایی'),
        ),
        migrations.AlterField(
            model_name='amazonproduct',
            name='base_price',
            field=models.FloatField(blank=True, null=True, verbose_name='قیمت پایه'),
        ),
        migrations.AlterField(
            model_name='amazonproduct',
            name='shipping_price',
            field=models.FloatField(blank=True, null=True, verbose_name='قیمت پایه حمل و نقل از آمازون'),
        ),
    ]
