# Generated by Django 4.2.7 on 2023-12-01 13:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('amazon', '0007_remove_amazonproduct_final_price_in_toman_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='amazonproduct',
            name='get_new_details_from_rainforest_api',
        ),
    ]
