# Generated by Django 4.2.7 on 2023-12-01 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('amazon', '0008_remove_amazonproduct_get_new_details_from_rainforest_api'),
    ]

    operations = [
        migrations.AlterField(
            model_name='amazonproduct',
            name='rating_score',
            field=models.FloatField(blank=True, null=True, verbose_name='امتیاز محصول'),
        ),
    ]
