# Generated by Django 4.2.7 on 2023-12-03 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('amazon', '0010_alter_amazonproduct_currency_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='cat_image',
            field=models.ImageField(blank=True, null=True, upload_to='categories/', verbose_name='تصویر دسته'),
        ),
    ]
