# Generated by Django 4.2.7 on 2023-12-04 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('amazon', '0011_category_cat_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='amazonproduct',
            name='asin',
            field=models.CharField(max_length=255, unique=True, verbose_name='ASIN'),
        ),
    ]
