# Generated by Django 4.2.7 on 2023-12-17 20:46

from django.db import migrations
import django_jalali.db.models


class Migration(migrations.Migration):

    dependencies = [
        ('amazon', '0013_alter_amazonproduct_asin'),
    ]

    operations = [
        migrations.AlterField(
            model_name='amazonproduct',
            name='updated_at',
            field=django_jalali.db.models.jDateTimeField(auto_now=True, verbose_name='تاریخ بروزرسانی'),
        ),
    ]
