# Generated by Django 4.2.7 on 2023-12-25 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('amazon', '0014_alter_amazonproduct_updated_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='amazonproduct',
            name='keywords_flat',
            field=models.TextField(blank=True, null=True, verbose_name='کلمات کلیدی بصورت یکجا'),
        ),
    ]
