# Generated by Django 4.2.7 on 2023-12-28 13:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('amazon', '0015_amazonproduct_keywords_flat'),
    ]

    operations = [
        migrations.AddField(
            model_name='amazonproduct',
            name='discount_percentage',
            field=models.IntegerField(blank=True, null=True, verbose_name='درصد تخفیف'),
        ),
        migrations.AddField(
            model_name='amazonproduct',
            name='seo_description',
            field=models.CharField(blank=True, max_length=1000, null=True, verbose_name='seo_description'),
        ),
        migrations.AddField(
            model_name='amazonproduct',
            name='seo_keywords',
            field=models.CharField(blank=True, max_length=1000, null=True, verbose_name='seo_keywords'),
        ),
        migrations.AddField(
            model_name='amazonproduct',
            name='seo_title',
            field=models.CharField(blank=True, max_length=1000, null=True, verbose_name='seo_title'),
        ),
        migrations.AddField(
            model_name='amazonproduct',
            name='slug',
            field=models.CharField(blank=True, max_length=1000, null=True, verbose_name='slug'),
        ),
    ]
