# Generated by Django 4.2.7 on 2023-12-28 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('amazon', '0016_amazonproduct_discount_percentage_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='keyword',
            options={'verbose_name': 'کلمه برجسته', 'verbose_name_plural': 'کلمات برجسته'},
        ),
        migrations.AlterField(
            model_name='amazonproduct',
            name='keywords',
            field=models.ManyToManyField(blank=True, related_name='product_keywords', to='amazon.keyword', verbose_name='کلمات برجسته'),
        ),
        migrations.AlterField(
            model_name='amazonproduct',
            name='keywords_flat',
            field=models.TextField(blank=True, null=True, verbose_name='کلمات برجسته بصورت یکجا'),
        ),
    ]
