# Generated by Django 4.2.7 on 2024-01-02 12:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('amazon', '0017_alter_keyword_options_alter_amazonproduct_keywords_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='amazonproduct',
            name='discounted_price',
            field=models.FloatField(blank=True, null=True, verbose_name='قیمت تخفیف خورده'),
        ),
        migrations.AddField(
            model_name='amazonproduct',
            name='variants',
            field=models.TextField(blank=True, null=True, verbose_name='سایز و رنگ'),
        ),
        migrations.AddField(
            model_name='amazonproduct',
            name='variants_asins_flat',
            field=models.TextField(blank=True, null=True, verbose_name='asin های سایز و رنگ'),
        ),
        migrations.AlterField(
            model_name='amazonproduct',
            name='seo_description',
            field=models.TextField(blank=True, null=True, verbose_name='seo_description'),
        ),
        migrations.AlterField(
            model_name='amazonproduct',
            name='seo_keywords',
            field=models.TextField(blank=True, null=True, verbose_name='seo_keywords'),
        ),
        migrations.AlterField(
            model_name='amazonproduct',
            name='seo_title',
            field=models.TextField(blank=True, null=True, verbose_name='seo_title'),
        ),
        migrations.AlterField(
            model_name='amazonproduct',
            name='slug',
            field=models.TextField(blank=True, null=True, verbose_name='slug'),
        ),
        migrations.AlterField(
            model_name='amazonproduct',
            name='title_fa',
            field=models.TextField(blank=True, null=True, verbose_name='عنوان فارسی'),
        ),
    ]
