# Generated by Django 4.2.7 on 2024-01-02 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('amazon', '0018_amazonproduct_discounted_price_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='amazonproduct',
            name='has_size_guide',
            field=models.TextField(blank=True, null=True, verbose_name='has_size_guide'),
        ),
        migrations.AddField(
            model_name='amazonproduct',
            name='size_guide_html',
            field=models.TextField(blank=True, null=True, verbose_name='size_guide_html'),
        ),
        migrations.AlterField(
            model_name='amazonproduct',
            name='variants',
            field=models.TextField(blank=True, null=True, verbose_name='variants'),
        ),
        migrations.AlterField(
            model_name='amazonproduct',
            name='variants_asins_flat',
            field=models.TextField(blank=True, null=True, verbose_name='variants_asins_flat'),
        ),
    ]
