# Generated by Django 4.2.7 on 2024-01-02 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('amazon', '0019_amazonproduct_has_size_guide_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='amazonproduct',
            name='downloaded_documents',
            field=models.BooleanField(default=False, verbose_name='داکیومنت ها دانلود شده'),
        ),
        migrations.AddField(
            model_name='amazonproduct',
            name='downloaded_images',
            field=models.BooleanField(default=False, verbose_name='سایر تصاویر دانلود شده'),
        ),
    ]
