# Generated by Django 4.2.7 on 2024-01-04 10:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('amazon', '0020_amazonproduct_downloaded_documents_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='children',
            field=models.ManyToManyField(blank=True, to='amazon.category', verbose_name='زیرمجموعه های اول'),
        ),
    ]
