# Generated by Django 4.2.7 on 2024-01-04 10:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('amazon', '0021_category_children'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='children',
            field=models.ManyToManyField(blank=True, editable=False, to='amazon.category', verbose_name='زیرمجموعه ها'),
        ),
    ]
