# Generated by Django 4.2.7 on 2024-01-04 10:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('amazon', '0022_alter_category_children'),
    ]

    operations = [
        migrations.AlterField(
            model_name='amazonproduct',
            name='title_en',
            field=models.TextField(blank=True, null=True, verbose_name='عنوان انگلیسی'),
        ),
    ]
