# Generated by Django 4.2.7 on 2024-01-04 18:02

from django.db import migrations, models
import django_jalali.db.models


class Migration(migrations.Migration):

    dependencies = [
        ('amazon', '0023_alter_amazonproduct_title_en'),
    ]

    operations = [
        migrations.CreateModel(
            name='AddAmazonProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('asin', models.CharField(blank=True, max_length=255, null=True, verbose_name='asin')),
                ('link', models.CharField(max_length=255, verbose_name='link')),
                ('created_at', django_jalali.db.models.jDateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
            ],
            options={
                'verbose_name': 'افزودن محصول آمازون',
                'verbose_name_plural': 'افزودن محصولات آمازون',
                'ordering': ['-created_at'],
            },
        ),
    ]
