# Generated by Django 4.2.7 on 2024-01-04 18:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('amazon', '0024_addamazonproduct'),
    ]

    operations = [
        migrations.AlterField(
            model_name='addamazonproduct',
            name='link',
            field=models.CharField(max_length=1000, verbose_name='link'),
        ),
    ]
