# Generated by Django 4.2.7 on 2024-01-07 12:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('amazon', '0026_remove_category_children'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='children',
            field=models.TextField(blank=True, editable=False, null=True, verbose_name='چایلد ها'),
        ),
    ]
