# Generated by Django 4.2.7 on 2024-01-07 12:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('amazon', '0027_category_children'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='children',
        ),
    ]
