# Generated by Django 4.2.7 on 2024-01-25 12:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('amazon', '0028_remove_category_children'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='amazonproduct',
            options={'ordering': ['-created_at'], 'verbose_name': 'محصول آمازون', 'verbose_name_plural': 'محصولات آمازون'},
        ),
    ]
