# Generated by Django 4.2.7 on 2023-12-19 09:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ticket', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='status',
            field=models.CharField(choices=[('ایجاد شده', 'ایجاد شده'), ('در حال بررسی', 'در حال بررسی'), ('پاسخ ادمین', 'پاسخ ادمین'), ('بسته شده', 'بسته شده'), ('پاسخ کاربر', 'پاسخ کاربر')], default='pending', max_length=255, verbose_name='وضعیت تیکت'),
        ),
    ]
