# Generated by Django 4.2.7 on 2024-01-07 12:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('ticket', '0003_alter_ticket_created_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='belong_to',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, related_name='ticket_belong_to', to=settings.AUTH_USER_MODEL, verbose_name='متعلق به'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='ticket',
            name='has_seen_by_user',
            field=models.BooleanField(default=False, verbose_name='دیده شده توسط کاربر'),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='created_by',
            field=models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='ticket_created_by', to=settings.AUTH_USER_MODEL, verbose_name='ساخته شده توسط'),
        ),
    ]
